#+title: Сравнение методов коммуникации между процессами в среде Linux

* Правила оформления

Расчетно-пояснительная записка должна иметь объем 20-30 листов текста на листах
формата А4. Записка должна содержать следующие разделы:

1. 1 Введение
2. 10 Обзор предметной области, алгоритмов и технологий: описания подходов к
   решению задачи
3. >=8 Конструкторский ("разработка ...."): обоснованный выбор алгоритма,
   подробно его применение в данной задаче, проектирование архитектуры и
   интерфейсов
4. >=8 Технологический ("реализация ...") обоснование выбранного языка,
   технологий и сторонних библиотек, ключевые моменты реализации, руководство
   администратора и руководство пользователя
5. 4 страницы Тестирование тесты корректности и сложности/производительности
6. 1-2 Заключение краткие выводы по результатам выполнения курсового проекта и
   предложения по их использованию, дальнейшему развитию или модификации
   разработанного комплекса программ, а также критическую оценку достигнутых
   результатов

Кроме того, записка должна иметь содержание, список использованной литературы,
а также в нее могут входить различные приложения.

Во введении обосновывается
актуальность темы, а также формулируется основная цель курсового проекта. Объём
введения должен составлять 1-2 листа.

В обзорном разделе проводится исследование предметной области, с которой связан
данный курсовой проект, рассматриваются основные существующие алгоритмы и
технологии, позволяющие решить поставленную в рамках курсового проектирования
задачу. Объём обзорного раздела должен составлять около 10 листов.

В конструкторском разделе на основе сделанного во введении обзора проводится
обоснованный выбор предлагаемого алгоритма, подробно описывается его
использование применительно к решаемой задаче. Также производится проектирование
архитектуры и модулей разрабатываемого приложения или пакета программ,
интерфейсов их взаимодействия, определяются форматы представления входных и
выходных данных, разрабатываются структуры данных для их внутреннего
представления. В данном разделе расчётно-пояснительной записки могут выполняться
расчеты для определения объемов памяти, необходимой для хранения исходных
данных, промежуточных и окончательных результатов, а также расчеты, позволяющие
оценить теоретическую сложность реализуемых алгоритмов. Объем конструкторской
части должен составлять 35-55% всего объема расчётно-пояснительной записки.

Технологический раздел должен содержать обоснование выбранных для реализации
комплекса программ языков программирования, технологий и сторонних библиотек.
Для полноты изложения приводятся ключевые моменты программной реализации
разрабатываемых программ. В технологический раздел также включаются руководство
администратора и руководство пользователя.

Руководство администратора должно включать описание процедуры инсталляции и
деинсталляции приложения, параметры запуска из командной строки, перечень
требований к аппаратному и системному программному обеспечению, наличию
каких-либо сторонних приложений или библиотек.

Руководство пользователя должно содержать подробное описание графического и/или
командного интерфейса разработанного приложения, перечень сообщений об ошибках с
их описанием. В случае разработки библиотеки функций, а не пользовательского или
системного приложения, руководство пользователя заменяется на описание
программного интерфейса (API) библиотеки.

Если руководство администратора и/или руководство пользователя имеют
значительный объем, они переносятся из технологического раздела
расчётно-пояснительной записки в приложения. Объем технологического раздела
расчётно-пояснительной записки составляет 35-40%.

Раздел тестирования, во первых, должен содержать разработку и выполнение тестов,
подтверждающих работоспособность созданного программного обеспечения. Во-вторых,
в нем должны быть приведены результаты теоретического или экспериментального
исследования, выполненного в ходе курсового проектирования. Например, это могут
быть результаты, полученные при исследовании математического метода, положенного
в основу разработанного алгоритма, или оценка временных и иных характеристик
комплекса программ (алгоритма) в зависимости от особенностей входных данных.
Объем раздела тестирования составляет 15-20%.

Заключение расчётно-пояснительной записки должно содержать краткие выводы по
результатам выполнения курсового проекта и предложения по их использованию,
дальнейшему развитию или модификации разработанного комплекса программ, а также
критическую оценку достигнутых результатов. Объём заключения не должен превышать
1-2 листов.

В приложениях даются листинги программ пакета или его наиболее интересных
составляющих частей. При наличии объёмных аналитических результатов их таблицы,
графики, диаграммы также приводятся в приложениях. Представленные результаты
должны сопровождаться указанием исходных данных, для которых они были получены.

Все разделы работы должны быть увязаны тесным образом между собой и представлять
собой единое законченное целое. Материал записки должен излагаться грамотным
техническим языком. За принятые решения, правильность выполненных расчетов и
сделанных выводов ответственность несет автор курсового проекта – студент.

* Сборка

#+begin_src sh
cmake .. -D CMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -D BASE_LINK_FLAGS='-static-libstdc++;-static-libgcc;-fno-omit-frame-pointer' -D BASE_COMPILE_FLAGS='-fno-omit-frame-pointer'

cmake .. -D CMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -D BASE_LINK_FLAGS='-static-libstdc++;-static-libgcc' -D BASE_COMPILE_FLAGS=''

./bin/benchmarks --benchmark_min_warmup_time=5 --benchmark_repetitions=5 --benchmark_out=out.json --benchmark_out_format=json

echo 0 > /proc/sys/kernel/randomize_va_space
echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo



#+end_src
